// Generated by sync-pics.ts — do not edit manually

interface ExifData {
	camera: string | null;
	aperture: number | null;
	shutterSpeed: string | null;
	iso: number | null;
	focalLength: number | null;
	dateTaken: string | null;
}

interface ImageVariant {
	width: number;
	format: 'webp' | 'jpeg';
	url: string;
	original?: boolean;
	size?: number;
}

interface ManifestEntry {
	id: string;
	hash: string;
	originalWidth: number;
	originalHeight: number;
	alt: string;
	exif: ExifData;
	variants: ImageVariant[];
}

interface Manifest {
	version: number;
	r2BaseUrl: string;
	images: ManifestEntry[];
}

const manifest: Manifest = {
	version: 1,
	r2BaseUrl: 'https://assets.jsn.cam',
	images: [
		{
			id: 'PXL_20230720_033605781.NIGHT~2',
			hash: 'sha256:88448148170df3638ee5443ddd06c24b06e29302d15fc7b2a95c6551766ecc62',
			originalWidth: 3072,
			originalHeight: 4080,
			alt: '',
			exif: {
				camera: 'Google Pixel 6',
				aperture: 1.85,
				shutterSpeed: '15.999575',
				iso: 2816,
				focalLength: 6.81,
				dateTaken: '2023-07-20'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/88448148/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/88448148/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/88448148/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/88448148/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/88448148/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/88448148/800.jpg'
				},
				{
					width: 3072,
					format: 'jpeg',
					url: '/pics/88448148/3072.jpg',
					original: true,
					size: 3159868
				}
			]
		},
		{
			id: 'unity',
			hash: 'sha256:30eaa6cd839673b7c014227cc640cd244b141b19be1ca9873c5207c0c237e18e',
			originalWidth: 6000,
			originalHeight: 4000,
			alt: '',
			exif: {
				camera: 'Canon EOS Rebel T7',
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/30eaa6cd/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/30eaa6cd/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/30eaa6cd/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/30eaa6cd/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/30eaa6cd/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/30eaa6cd/800.jpg'
				},
				{
					width: 6000,
					format: 'jpeg',
					url: '/pics/30eaa6cd/6000.jpg',
					original: true,
					size: 8137603
				}
			]
		},
		{
			id: 'IMG_9555',
			hash: 'sha256:0242161e423e25a323a9d9901d34c5bfcef7aa727c707cdb792a7d4767dca017',
			originalWidth: 6000,
			originalHeight: 4000,
			alt: '',
			exif: {
				camera: 'Canon EOS Rebel T7',
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/0242161e/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/0242161e/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/0242161e/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/0242161e/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/0242161e/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/0242161e/800.jpg'
				},
				{
					width: 6000,
					format: 'jpeg',
					url: '/pics/0242161e/6000.jpg',
					original: true,
					size: 7876780
				}
			]
		},
		{
			id: 'PXL_20220404_221001861',
			hash: 'sha256:69b275ee02eba59c106e69fbbe4a7858bc35d53e023c828923a2cdbf0a052477',
			originalWidth: 2129,
			originalHeight: 3418,
			alt: '',
			exif: {
				camera: 'Google Pixel 6',
				aperture: 1.9,
				shutterSpeed: '1/240',
				iso: 42,
				focalLength: 6.81,
				dateTaken: '2022-04-04'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/69b275ee/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/69b275ee/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/69b275ee/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/69b275ee/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/69b275ee/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/69b275ee/800.jpg'
				},
				{
					width: 2129,
					format: 'jpeg',
					url: '/pics/69b275ee/2129.jpg',
					original: true,
					size: 3853256
				}
			]
		},
		{
			id: 'IMG_0013',
			hash: 'sha256:0e0e59e5060d0d5c598d741c705418dd5b5e386c4d987d1dc7d417d7cd969abe',
			originalWidth: 6000,
			originalHeight: 4000,
			alt: '',
			exif: {
				camera: 'Canon EOS Rebel T7',
				aperture: 5.6,
				shutterSpeed: '1/160',
				iso: 200,
				focalLength: 29,
				dateTaken: '2023-10-19'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/0e0e59e5/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/0e0e59e5/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/0e0e59e5/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/0e0e59e5/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/0e0e59e5/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/0e0e59e5/800.jpg'
				},
				{
					width: 6000,
					format: 'jpeg',
					url: '/pics/0e0e59e5/6000.jpg',
					original: true,
					size: 12465350
				}
			]
		},
		{
			id: 'space',
			hash: 'sha256:e05b0732feba9aead95413725772ec97c91b81d07769756035773c8f4c14df54',
			originalWidth: 6000,
			originalHeight: 4000,
			alt: '',
			exif: {
				camera: 'Canon EOS Rebel T7',
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/e05b0732/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/e05b0732/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/e05b0732/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/e05b0732/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/e05b0732/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/e05b0732/800.jpg'
				},
				{
					width: 6000,
					format: 'jpeg',
					url: '/pics/e05b0732/6000.jpg',
					original: true,
					size: 4740383
				}
			]
		},
		{
			id: 'DSCF0618',
			hash: 'sha256:8e1704b5f7c7d59afc7901920b6a4c61193134a9af67ca577cfe4ef3c4dc3894',
			originalWidth: 7728,
			originalHeight: 5152,
			alt: '',
			exif: {
				camera: 'FUJIFILM X100VI',
				aperture: 2,
				shutterSpeed: '1/512',
				iso: 500,
				focalLength: 23,
				dateTaken: '2026-02-02'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/8e1704b5/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/8e1704b5/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/8e1704b5/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/8e1704b5/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/8e1704b5/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/8e1704b5/800.jpg'
				},
				{
					width: 7728,
					format: 'jpeg',
					url: '/pics/8e1704b5/7728.jpg',
					original: true,
					size: 17801632
				}
			]
		},
		{
			id: '_MG_0577',
			hash: 'sha256:05631b76c6f88e14ca9bb18355ab3df5ef83d3ef38379669d258900198e34cf0',
			originalWidth: 6000,
			originalHeight: 4000,
			alt: '',
			exif: {
				camera: 'Canon EOS Rebel T7',
				aperture: 3.2,
				shutterSpeed: '1/1250',
				iso: 100,
				focalLength: 50,
				dateTaken: '2023-12-25'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/05631b76/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/05631b76/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/05631b76/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/05631b76/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/05631b76/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/05631b76/800.jpg'
				},
				{
					width: 6000,
					format: 'jpeg',
					url: '/pics/05631b76/6000.jpg',
					original: true,
					size: 7313751
				}
			]
		},
		{
			id: 'PXL_20251031_221431315',
			hash: 'sha256:18517937370defc46d33af5892eb7549220241a3d214512c3ddfb8b2c69ffa2c',
			originalWidth: 3072,
			originalHeight: 4080,
			alt: '',
			exif: {
				camera: 'Google Pixel 8',
				aperture: 1.68,
				shutterSpeed: '1/140',
				iso: 30,
				focalLength: 6.9,
				dateTaken: '2025-10-31'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/18517937/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/18517937/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/18517937/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/18517937/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/18517937/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/18517937/800.jpg'
				},
				{
					width: 3072,
					format: 'jpeg',
					url: '/pics/18517937/3072.jpg',
					original: true,
					size: 7311272
				}
			]
		},
		{
			id: '_MG_0564',
			hash: 'sha256:4f5e02f7c2e8bbfb77552c98f2b2f4e4bc32667cade2502f7c65b92f952bece2',
			originalWidth: 6000,
			originalHeight: 4000,
			alt: '',
			exif: {
				camera: 'Canon EOS Rebel T7',
				aperture: 2.8,
				shutterSpeed: '1/1250',
				iso: 100,
				focalLength: 50,
				dateTaken: '2023-12-25'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/4f5e02f7/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/4f5e02f7/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/4f5e02f7/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/4f5e02f7/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/4f5e02f7/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/4f5e02f7/800.jpg'
				},
				{
					width: 6000,
					format: 'jpeg',
					url: '/pics/4f5e02f7/6000.jpg',
					original: true,
					size: 9076846
				}
			]
		},
		{
			id: 'DSCF0479',
			hash: 'sha256:8f8f10e557286d81b750cabf2adcc5447301b04986c6f2b6a346816d3b4bd036',
			originalWidth: 2048,
			originalHeight: 1365,
			alt: '',
			exif: {
				camera: null,
				aperture: null,
				shutterSpeed: null,
				iso: null,
				focalLength: null,
				dateTaken: null
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/8f8f10e5/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/8f8f10e5/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/8f8f10e5/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/8f8f10e5/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/8f8f10e5/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/8f8f10e5/800.jpg'
				},
				{
					width: 2048,
					format: 'jpeg',
					url: '/pics/8f8f10e5/2048.jpg',
					original: true,
					size: 1223984
				}
			]
		},
		{
			id: 'PXL_20240414_234010698',
			hash: 'sha256:84a40964c11c58e0d8e39f49a8c39736b0ef76cc17bd5fc0676d746cb96eec1b',
			originalWidth: 3072,
			originalHeight: 4080,
			alt: '',
			exif: {
				camera: 'Google Pixel 8',
				aperture: 2.2,
				shutterSpeed: '1/90',
				iso: 124,
				focalLength: 1.95,
				dateTaken: '2024-04-14'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/84a40964/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/84a40964/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/84a40964/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/84a40964/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/84a40964/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/84a40964/800.jpg'
				},
				{
					width: 3072,
					format: 'jpeg',
					url: '/pics/84a40964/3072.jpg',
					original: true,
					size: 6970034
				}
			]
		},
		{
			id: 'PXL_20250829_235850782',
			hash: 'sha256:627b0ff2c03ad92d6fb658032ea472192a8e38aa16bcb82c095d45cee3b985dd',
			originalWidth: 3072,
			originalHeight: 4080,
			alt: '',
			exif: {
				camera: 'Google Pixel 8',
				aperture: 1.68,
				shutterSpeed: '1/120',
				iso: 84,
				focalLength: 6.9,
				dateTaken: '2025-08-29'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/627b0ff2/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/627b0ff2/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/627b0ff2/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/627b0ff2/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/627b0ff2/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/627b0ff2/800.jpg'
				},
				{
					width: 3072,
					format: 'jpeg',
					url: '/pics/627b0ff2/3072.jpg',
					original: true,
					size: 4615071
				}
			]
		},
		{
			id: '_DSF0888',
			hash: 'sha256:a1949dbe43f40ca990589dbfdf148422d5acda8efe4d54acb30010a617b9d86a',
			originalWidth: 7728,
			originalHeight: 5152,
			alt: '',
			exif: {
				camera: 'FUJIFILM X100VI',
				aperture: 5,
				shutterSpeed: '1/500',
				iso: 125,
				focalLength: 23,
				dateTaken: '2026-02-04'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/a1949dbe/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/a1949dbe/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/a1949dbe/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/a1949dbe/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/a1949dbe/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/a1949dbe/800.jpg'
				},
				{
					width: 7728,
					format: 'jpeg',
					url: '/pics/a1949dbe/7728.jpg',
					original: true,
					size: 18482639
				}
			]
		},
		{
			id: 'PXL_20220626_030332663.NIGHT',
			hash: 'sha256:08843f9259732a04a6d5164f8da3cda1a66b7b885caa9d1e1b14e29e56d02756',
			originalWidth: 4080,
			originalHeight: 3072,
			alt: '',
			exif: {
				camera: 'Google Pixel 6',
				aperture: 1.85,
				shutterSpeed: '15.999575',
				iso: 517,
				focalLength: 6.81,
				dateTaken: '2022-06-26'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/08843f92/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/08843f92/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/08843f92/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/08843f92/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/08843f92/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/08843f92/800.jpg'
				},
				{
					width: 4080,
					format: 'jpeg',
					url: '/pics/08843f92/4080.jpg',
					original: true,
					size: 5853367
				}
			]
		},
		{
			id: 'PXL_20251103_220514644~2',
			hash: 'sha256:6f84485aec6992482f7fb96330978faeaacc633bcffea1b358c8cccbed473c07',
			originalWidth: 3072,
			originalHeight: 4080,
			alt: '',
			exif: {
				camera: 'Google Pixel 8',
				aperture: 1.68,
				shutterSpeed: '1/260',
				iso: 27,
				focalLength: 6.9,
				dateTaken: '2025-11-03'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/6f84485a/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/6f84485a/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/6f84485a/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/6f84485a/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/6f84485a/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/6f84485a/800.jpg'
				},
				{
					width: 3072,
					format: 'jpeg',
					url: '/pics/6f84485a/3072.jpg',
					original: true,
					size: 2390674
				}
			]
		},
		{
			id: 'IMG_9884',
			hash: 'sha256:587bc9851709c39bf1510357881fc778b0f0d03bb1503912cd03f8cde01823e1',
			originalWidth: 6000,
			originalHeight: 3460,
			alt: '',
			exif: {
				camera: 'Canon EOS Rebel T7',
				aperture: 4.5,
				shutterSpeed: '1/60',
				iso: 400,
				focalLength: 28,
				dateTaken: '2023-10-17'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/587bc985/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/587bc985/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/587bc985/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/587bc985/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/587bc985/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/587bc985/800.jpg'
				},
				{
					width: 6000,
					format: 'jpeg',
					url: '/pics/587bc985/6000.jpg',
					original: true,
					size: 6384048
				}
			]
		},
		{
			id: 'PXL_20230719_022112889.NIGHT',
			hash: 'sha256:9076af7bdfdc2f7016f8a67b065a60a69b0415772092cba12a1eee52ddf437ba',
			originalWidth: 3072,
			originalHeight: 4080,
			alt: '',
			exif: {
				camera: 'Google Pixel 6',
				aperture: 1.9,
				shutterSpeed: '16',
				iso: 2056,
				focalLength: 6.81,
				dateTaken: '2023-07-19'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/9076af7b/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/9076af7b/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/9076af7b/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/9076af7b/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/9076af7b/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/9076af7b/800.jpg'
				},
				{
					width: 3072,
					format: 'jpeg',
					url: '/pics/9076af7b/3072.jpg',
					original: true,
					size: 3824662
				}
			]
		},
		{
			id: 'PXL_20251106_012413214',
			hash: 'sha256:cf63f7fcfdf974963281778ee51e9e789640b2021b6dbf96b76cd2c5be7d9aaa',
			originalWidth: 4080,
			originalHeight: 3072,
			alt: '',
			exif: {
				camera: 'Google Pixel 8',
				aperture: 1.68,
				shutterSpeed: '1/99',
				iso: 377,
				focalLength: 6.9,
				dateTaken: '2025-11-05'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/cf63f7fc/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/cf63f7fc/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/cf63f7fc/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/cf63f7fc/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/cf63f7fc/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/cf63f7fc/800.jpg'
				},
				{
					width: 4080,
					format: 'jpeg',
					url: '/pics/cf63f7fc/4080.jpg',
					original: true,
					size: 4267507
				}
			]
		},
		{
			id: 'PXL_20240514_232351202.PORTRAIT',
			hash: 'sha256:f6e6d57ab22f1857376d1f0cc2e7a9bfc7695ea19b3dec36a5f151814b5fa3f3',
			originalWidth: 4080,
			originalHeight: 3072,
			alt: '',
			exif: {
				camera: 'Google Pixel 8',
				aperture: 1.68,
				shutterSpeed: '1/4405',
				iso: 18,
				focalLength: 6.9,
				dateTaken: '2024-05-14'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/f6e6d57a/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/f6e6d57a/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/f6e6d57a/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/f6e6d57a/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/f6e6d57a/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/f6e6d57a/800.jpg'
				},
				{
					width: 4080,
					format: 'jpeg',
					url: '/pics/f6e6d57a/4080.jpg',
					original: true,
					size: 4820248
				}
			]
		},
		{
			id: 'PXL_20221009_195927011',
			hash: 'sha256:2b9c3201c29731c3dc65a11b11d98b99ef6346aadfd8aba4d474f9014336a5b8',
			originalWidth: 4080,
			originalHeight: 3072,
			alt: '',
			exif: {
				camera: 'Google Pixel 6',
				aperture: 1.85,
				shutterSpeed: '1/435',
				iso: 48,
				focalLength: 6.81,
				dateTaken: '2022-10-09'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/2b9c3201/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/2b9c3201/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/2b9c3201/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/2b9c3201/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/2b9c3201/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/2b9c3201/800.jpg'
				},
				{
					width: 4080,
					format: 'jpeg',
					url: '/pics/2b9c3201/4080.jpg',
					original: true,
					size: 5294860
				}
			]
		},
		{
			id: '_DSF0936',
			hash: 'sha256:aea7f033d81128a5bd469ca2f1d5196b1b9f8145ea58d2ccd9a43ba23df420cf',
			originalWidth: 5152,
			originalHeight: 7728,
			alt: '',
			exif: {
				camera: 'FUJIFILM X100VI',
				aperture: 2,
				shutterSpeed: '1/1250',
				iso: 500,
				focalLength: 23,
				dateTaken: '2026-02-05'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/aea7f033/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/aea7f033/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/aea7f033/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/aea7f033/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/aea7f033/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/aea7f033/800.jpg'
				},
				{
					width: 5152,
					format: 'jpeg',
					url: '/pics/aea7f033/5152.jpg',
					original: true,
					size: 15805465
				}
			]
		},
		{
			id: 'PXL_20250001',
			hash: 'sha256:4c20a135e32081ddee6cd91d9193c37dc3706415709f8f3b35c0f05866a563a2',
			originalWidth: 4000,
			originalHeight: 6000,
			alt: '',
			exif: {
				camera: 'Canon EOS Rebel T7',
				aperture: 5.6,
				shutterSpeed: '1/50',
				iso: 400,
				focalLength: 47,
				dateTaken: '2023-10-08'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/4c20a135/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/4c20a135/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/4c20a135/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/4c20a135/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/4c20a135/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/4c20a135/800.jpg'
				},
				{
					width: 4000,
					format: 'jpeg',
					url: '/pics/4c20a135/4000.jpg',
					original: true,
					size: 7980943
				}
			]
		},
		{
			id: 'IMG_0036',
			hash: 'sha256:80e4cf2dea19b28ed52d8b3191a20b85ae3062e3d5a24c7695da3751aa26ec4d',
			originalWidth: 6000,
			originalHeight: 4000,
			alt: '',
			exif: {
				camera: 'Canon EOS Rebel T7',
				aperture: 5.6,
				shutterSpeed: '1/160',
				iso: 200,
				focalLength: 55,
				dateTaken: '2023-10-19'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/80e4cf2d/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/80e4cf2d/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/80e4cf2d/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/80e4cf2d/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/80e4cf2d/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/80e4cf2d/800.jpg'
				},
				{
					width: 6000,
					format: 'jpeg',
					url: '/pics/80e4cf2d/6000.jpg',
					original: true,
					size: 9999748
				}
			]
		},
		{
			id: 'PXL_20240514_232408454.PORTRAIT.ORIGINAL',
			hash: 'sha256:3a1be024fa22d091c75b9f16417ec943eb23eb62b1c34f522ddc75e525600cd2',
			originalWidth: 4080,
			originalHeight: 3072,
			alt: '',
			exif: {
				camera: 'Google Pixel 8',
				aperture: 1.68,
				shutterSpeed: '1/618',
				iso: 19,
				focalLength: 6.9,
				dateTaken: '2024-05-14'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/3a1be024/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/3a1be024/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/3a1be024/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/3a1be024/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/3a1be024/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/3a1be024/800.jpg'
				},
				{
					width: 4080,
					format: 'jpeg',
					url: '/pics/3a1be024/4080.jpg',
					original: true,
					size: 4037774
				}
			]
		},
		{
			id: 'PXL_20250311_221838769',
			hash: 'sha256:575f2958402133f20b1765701d07b63ccb051c22d11675845e28a633c44c8ffe',
			originalWidth: 4080,
			originalHeight: 3072,
			alt: '',
			exif: {
				camera: 'Google Pixel 8',
				aperture: 1.68,
				shutterSpeed: '1/498',
				iso: 18,
				focalLength: 6.9,
				dateTaken: '2025-03-11'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/575f2958/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/575f2958/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/575f2958/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/575f2958/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/575f2958/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/575f2958/800.jpg'
				},
				{
					width: 4080,
					format: 'jpeg',
					url: '/pics/575f2958/4080.jpg',
					original: true,
					size: 7581681
				}
			]
		},
		{
			id: 'PXL_20220918_221838148.PORTRAIT',
			hash: 'sha256:3c5af4f01b2f595b63d846bc7be0a92bc16ff38a49430d787bd13392453f3c9e',
			originalWidth: 4080,
			originalHeight: 3072,
			alt: '',
			exif: {
				camera: 'Google Pixel 6',
				aperture: 1.85,
				shutterSpeed: '1/786',
				iso: 30,
				focalLength: 6.81,
				dateTaken: '2022-09-18'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/3c5af4f0/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/3c5af4f0/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/3c5af4f0/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/3c5af4f0/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/3c5af4f0/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/3c5af4f0/800.jpg'
				},
				{
					width: 4080,
					format: 'jpeg',
					url: '/pics/3c5af4f0/4080.jpg',
					original: true,
					size: 4287464
				}
			]
		},
		{
			id: 'IMG_0542',
			hash: 'sha256:e3b9bb4158c8a31c6d90080748bec0b5168303016728a6077d013584f9ed9caf',
			originalWidth: 3600,
			originalHeight: 2700,
			alt: '',
			exif: {
				camera: 'Apple iPhone 16 Pro',
				aperture: 1.7799999713880652,
				shutterSpeed: '1/184',
				iso: 200,
				focalLength: 6.764999865652793,
				dateTaken: '2024-11-24'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/e3b9bb41/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/e3b9bb41/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/e3b9bb41/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/e3b9bb41/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/e3b9bb41/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/e3b9bb41/800.jpg'
				},
				{
					width: 3600,
					format: 'jpeg',
					url: '/pics/e3b9bb41/3600.jpg',
					original: true,
					size: 3062718
				}
			]
		},
		{
			id: 'PXL_20251114_010033442',
			hash: 'sha256:5351892553140e666c6970a360609abd96ebd1f7e97f312b8cc7aa828ae95cbc',
			originalWidth: 4080,
			originalHeight: 3072,
			alt: '',
			exif: {
				camera: 'Google Pixel 8',
				aperture: 1.68,
				shutterSpeed: '1/120',
				iso: 202,
				focalLength: 6.9,
				dateTaken: '2025-11-13'
			},
			variants: [
				{
					width: 2000,
					format: 'webp',
					url: '/pics/53518925/2000.webp'
				},
				{
					width: 2000,
					format: 'jpeg',
					url: '/pics/53518925/2000.jpg'
				},
				{
					width: 1200,
					format: 'webp',
					url: '/pics/53518925/1200.webp'
				},
				{
					width: 1200,
					format: 'jpeg',
					url: '/pics/53518925/1200.jpg'
				},
				{
					width: 800,
					format: 'webp',
					url: '/pics/53518925/800.webp'
				},
				{
					width: 800,
					format: 'jpeg',
					url: '/pics/53518925/800.jpg'
				},
				{
					width: 4080,
					format: 'jpeg',
					url: '/pics/53518925/4080.jpg',
					original: true,
					size: 5105756
				}
			]
		}
	]
};

export default manifest;
